### PR TITLE
[CLEANUP] Separate the CSS selector and declarations.

### PR DESCRIPTION
**Pull request by oliverklee**
This change changes constructs like this:

p { color: #000; }

into this:

p {
  color: #000;
}

In addition, the indentation of the changed lines is changed from tabs
to spaces.

### CODE REVIEW

**Comment by djesse** [comment]
These changes are highly dependent on personal taste. I won't change indention from tabs to spaces and there's nothing wrong with single line CSS statements.

**Comment by oliverklee** [comment]
Okay, so apart from having tabs for indentation, what style guide does the Sass code follow (or should follow)?

I propose following the default settings of scss-lint (this will make the task of automatically checking the code a lot easier).

**Comment by michsch** [comment]
> These changes are highly dependent on personal taste.

Normally i would agree, but if there is a well known and accepted style guide, i'd prefer it's default guideline.

**Comment by jensgro** [comment]
If there is no possibility to change the settings of scss-lint in this aspect I guess you'll have a problem, but that shouldn't bother the project. 

Maybe we can file a coding guideline for YAML in the future but in the meantine this isn't necessary and we shouldn't change the files just because of scss-lint.

**Pull request closed without merging**
